### PR TITLE
fix a bug and add new unit test

### LINKED ISSUE #69: columnInfoMap bug
Now in master there is a bug concerning `columnInfoMap` and `getValueByName`: 
(1) `columnInfoMap` is now assigned under the effect of `slimit` & `soffset`
(2) in `getValueByName` there is an assignment `int tmp = columnInfoMap.get(columnName)+seriesOffset;`

The bug is exposed when executing sql e.g., `select *,s1,s0 from root.vehicle.d0 slimit 3 soffset 2` (Propose `*` expands to be `s0,s1,s2`) :
```
columnInfoList = [Time, root.vehicle.d0.s2, root.vehicle.d0.s1, root.vehicle.d0.s0]
columnInfoMap = [Time->1, 
root.vehicle.d0.s2->2, 
root.vehicle.d0.s1->3, 
root.vehicle.d0.s0->4]
tmp=columnInfoMap.get("root.vehicle.d0.s1") + 2 = 3 + 2 = 5 -> thus resulting in the null result.
```

**The core of the problem is that the assignment process of `columnInfoMap` must not be affected by `slimit` & `soffset` in order to be consistent with the actual order of data in `record`.** 

In the example shown above, the fix means that `columnInfoMap` should be: 
```
columnInfoMap = [Time->1, 
root.vehicle.d0.s0->2, 
root.vehicle.d0.s1->3, 
root.vehicle.d0.s2->4]
```

### PR DESCRIPTION
**Pull request by LeiRui**
close #69

### CODE REVIEW

**Comment by LeiRui** [comment]
wait for review. @MyXOF

**Review by MyXOF — APPROVED** [review]

**Review by MyXOF — APPROVED** [review]

**Review by MyXOF — APPROVED** [review]

**Comment by MyXOF** [comment]
+1

**Comment by MyXOF** [comment]
close #69

**Comment by MyXOF** [comment]
close #69

**Comment by MyXOF** [comment]
+1

**Comment by MyXOF** [comment]
+1

**Comment by MyXOF** [comment]
+1

**Comment by MyXOF** [comment]
+1

**Comment by MyXOF** [comment]
+1

**Pull request merged**
